### ISSUE TITLE
set_*label - command for ProfilePlot

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1298]
Originally reported by: **Katharina Wollenberg (Bitbucket: [kwollenberg](https://bitbucket.org/kwollenberg), GitHub: [kwollenberg](https://github.com/kwollenberg))**

----------------------------------------

Hi together, 

so far in yt, ProfilePlot does not have an "easy" way to set the plot axes labels individually. It would be nice to have in the future a command similar to the set_x/y/zlabel as is given for e.g. SlicePlot. 

Kind regards, 

Katharina   

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1298

**Comment by somnathrakshit** [comment]
Hi, I am interested in working with this. Could you guide me where to get started?

**Comment by cphyc** [comment]
Hi!
That's great thanks! 

You can find the api reference here http://yt-project.org/doc/reference/api/yt.visualization.profile_plotter.html#yt.visualization.profile_plotter.ProfilePlot (the code source is here http://yt-project.org/doc/_modules/yt/visualization/profile_plotter.html#ProfilePlot).

You probably have to hack the code so that it reads from its own attribute (set by `set_xlabel`) whenever found, or falls back to the default behaviour.

**Comment by ngoldbaum** [comment]
Closed by #1700
