### ISSUE TITLE
`take_log` works on generic field name, but not front end name

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1302]
Originally reported by: **Michael  Zingale (Bitbucket: [mzingale](https://bitbucket.org/mzingale), GitHub: Unknown)**

----------------------------------------

This script reads in a Castro (boxlib) file and makes two plots.  The goal is to not take the log.  For the first attempt, we disable log using the field `('boxlib', 'density')`.  For the next, we use `('gas', 'density').  

Note these are ailased to one another as the print shows:

```
On-Disk Field (boxlib, density): (units: g/cm**3, display_name: '\rho')
Alias Field for "('boxlib', 'density')" (gas, density): (units: g/cm**3, display_name: '\rho')
```

but only the one with `gas` successfully disables the log.

```
import yt

ds = yt.load("plt00000")

print(ds.fields.boxlib.density)
print(ds.fields.gas.density)

ds.index
ds.field_info['boxlib','density'].take_log = False

p = yt.SlicePlot(ds,"theta",'density')
p.save("densBoxLib.png")

ds = yt.load("plt00000")

ds.index
ds.field_info['gas','density'].take_log = False

p = yt.SlicePlot(ds,"theta", 'density')
p.save("densGas.png")
```

The test dataset is here:

http://bender.astro.sunysb.edu/random/plt00000.tgz

(for some reason, I can no longer open the datasets on the yt page, so something changed in the front end that I need to investigate separately, and/or, update the sample datasets)

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1302

**Comment by ngoldbaum** [comment]
So I think this actually works fine and the original issue was because of confusion about ambiguous field names. For example, the following script saves a plot in linear scale:

```
import yt

ds = yt.load("maestro_subCh_plt00248")

print(ds.fields.boxlib.density)
print(ds.fields.gas.density)

ds.index
ds.field_info['boxlib', 'density'].take_log = False

p = yt.SlicePlot(ds, "x", ('boxlib', 'density'))
p.save("densBoxLib.png")
```

They key difference from the plot in the issue as reported is that I'm creating the `SlicePlot` explicitly using `('boxlib', 'density')`. In the original issue, the `SlicePlot` gets created using the `density` field which gets resolved to `('gas', 'density')`. In the future we are planning to make such situations where a field access with a string is ambiguous raise an error to avoid confusion like this. I'm closing the issue but feel free to reopen if I've missed something.
