### ISSUE TITLE
PhasePlot is not redrawn on AxesGrids

### ISSUE THREAD

**Issue by pgrete** [yt-project/yt#1543]
### Bug report

**Bug summary**

AxesGrid remains empty when trying to add multiple PhasePlots according to the cookbook.

**Code for reproduction**
https://gist.github.com/pgrete/b5121bd8d621474f7dcb741199c4e1ec

**Version Information**

  * Operating System: SUSE Linux Enterprise Server 11
  * Python Version: Python 2.7.13 :: Continuum Analytics, Inc. 
  * yt version: Version = 3.5.dev0 Changeset = 089ce67cd554

**Comment by ngoldbaum** [comment]
@pgrete sorry for taking so long to look at this! @hyschive also ran into this recently so I took a look at this today.

One way to "fix" this is to add `p._plot_valid = False` before calling `p._setup_plots()`. However, while that causes the plot to be drawn on the `AxesGrid` axes, we still get an answer that isn't very good:

<img width="512" alt="image" src="https://user-images.githubusercontent.com/3126246/30942131-aac79152-a3ae-11e7-8411-3650c1449ed4.png">

I think this is happening because it turns `AxesGrid` doesn't support log-scaled axes. It may be possible to do this using a set of manually set up axes using e.g. `gridspec`.

So to resolve this, we need to figure out a recipe for making multipanel plots with possibly log-scaled axes.

**Comment by hyschive** [comment]
@pgrete @ngoldbaum it seems to work with the following minor modifications:

- Set `aspect=False` when calling `AxesGrid`
- Set the axis range explicitly, for example, `p.set_xlim( 1.0e-32, 2.0e-25 ); p.set_ylim( 1.0e1, 1.0e7 )`
- Attach the color axis only for the 0th grid: `if i == 0: plot.cax = grid.cbar_axes[i]`

![fig_multi_panel_phaseplot](https://user-images.githubusercontent.com/18057331/31199439-f0b0a064-a91c-11e7-9513-e1c8e8099849.png)

**Comment by ngoldbaum** [comment]
Cool! I think it would be worth adding the code for this as a cookbook example.

**Comment by hyschive** [comment]
Sure. I could do that if you don't mind.

BTW, it also seems that the axis properties can be modified only AFTER
calling p._setup_plots(). For example, putting
`plot.axes.xaxis.set_visible( False )` BEFORE p._setup_plots() seems to
have no effect at all. Do you know why? It might be worthwhile to clarify
this point in the cookbook as well.

**Comment by ngoldbaum** [comment]
Because `p._setup_plots()` is probably overriding those customizations.

See #1460 for a proposal for a much nicer API that would avoid these issues.

**Comment by hyschive** [comment]
Thanks for the clarification.


Nathan Goldbaum <notifications@github.com>於 2017年10月4日 週三，下午4:17寫道：
