### ISSUE TITLE
Problem add_particle_filter()

### ISSUE THREAD

**Issue by alegtz** [yt-project/yt#1544]
I have a Gadget simulation data, and I want to separate the particle types, but when I use a filter I have a problem.

This is the code:
 ```
  #python3 

  import yt
  import yt.units as unit
  
  def gas(pfilter, data):
        return data[(pfilter.filtered_type, 'particle_type')] == 0 


   yt.add_particle_filter("gas", function=gas, filtered_type='all', 
                       requires=["particle_type"])

  path="/home/ale/Simulaciones/lcdm_gas/"
  ds=yt.load(path+"snapshot_005")
  ds.add_particle_filter('gas')

```

And, returns

```
---------------------------------------------------------------------------
YTIllDefinedParticleFilter                Traceback (most recent call last)
<ipython-input-118-bdb332519f87> in <module>()
      1 #path="/home/ale/Simulaciones/lcdm_gas/"
      2 #ds=yt.GadgetDataset(path+"snapshot_005")
----> 3 ds.add_particle_filter('stars')

/home/ale/anaconda3/lib/python3.6/site-packages/yt/data_objects/static_output.py in add_particle_filter(self, filter)
    663             used = False
    664             for f in filter_registry[filter]:
--> 665                 used = self._setup_filtered_type(f)
    666                 if used:
    667                     filter = f

/home/ale/anaconda3/lib/python3.6/site-packages/yt/data_objects/static_output.py in _setup_filtered_type(self, filter)
    678         if not filter.available(self.derived_field_list):
    679             raise YTIllDefinedParticleFilter(
--> 680                 filter, filter.missing(self.derived_field_list))
    681         fi = self.field_info
    682         fd = self.field_dependencies

YTIllDefinedParticleFilter: 
The fields
	('all', 'particle_type'),
required by the "stars" particle filter, are not defined for this dataset.

```

**Comment by ngoldbaum** [comment]
What's the content of `ds.derived_field_list`? Does it include `('all', 'particle_type')`?

**Comment by alegtz** [comment]
I didn't look the content of ```ds.derived_field_list``` , but does not include ```('all', 'particle_type')```. 
 ```ds.derived_field_list``` has the division of  ```('Gas','Coordinates')``` and so on. 
In the command ̣```dir(ds)``` appears ```'particle_types'```.
Can I use a particle filter? Or I have to work with the own data filters?

**Comment by ngoldbaum** [comment]
Your particle filter needs to be defined in terms of fields that are available in your dataset. Perhaps based on particle mass or some other heuristic if there is no particle type field available for your data.

I'm going to close this issue since this isn't a yt bug. If you have further questions I'd encourage you to send an email to the yt-users mailing list. There are a number of people subscribed to the list who have expertise with Gadget data.

**Comment by ngoldbaum** [comment]
Also, if you're just trying to distinguish between different particle types, I don't think you need a particle filter at all for Gadget data, since the dataset itself separates the fields available on disk by particle type.

For example, for Gadget HDF5 data, you can access the SPH particle masses via the `('PartType0', 'particle_mass')` field. For Gadget Binary data, the field is named `('Gas', 'particle_mass')`.

I hope that makes things clearer.

**Comment by alegtz** [comment]
Thank you very much
