### ISSUE TITLE
Cannot use _switch_ds with a ParticlePlot

### ISSUE THREAD

**Issue by JBorrow** [yt-project/yt#1582]
### Bug report

**Bug summary**

Trying to create a movie following [this](http://yt-project.org/doc/cookbook/complex_plots.html?highlight=funcanimation) guide crashes when using a ParticlePlot, with the following error: ```AttributeError: 'TipsyDataset' object has no attribute 'Particle'```

**Code for reproduction**
```python
import yt

ds = yt.load("TipsyGalaxy/galaxy.00300")
ds2 = yt.load("TipsyGalaxy/galaxy.00300")

plot = yt.ParticlePlot(
    ds,
    ("Gas", "particle_position_x"),
    ("Gas", "particle_position_y"),
    ("Gas", "density"),
    width=6)

plot._switch_ds(ds2)

plot.save("test.png")
```

Note that this is not an issue for e.g. ProjectionPlots of the density which appear to work fine.

**Actual outcome**

```
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    plot._switch_ds(ds2)
  File "/Users/goldbaum/Documents/yt-git-fixes/yt/visualization/plot_container.py", line 325, in _switch_ds
    new_object = getattr(new_ds, name)(**kwargs)
AttributeError: 'TipsyDataset' object has no attribute 'Particle'
```

**Expected outcome**

A lovely plot.

**Version Information**

  * Operating System: MacOS 13.0.0 High Sierra
  * Python Version: 3.6.2
  * yt version: Dev/Source

**Comment by ngoldbaum** [comment]
Able to reproduce, had to edit your script a bit because support for your SWIFT data isn't in mainline yet.

**Comment by JBorrow** [comment]
After a little more investigation, this seems to be an issue with `data_source._type_name`; yt assumes that `ds._type_name` is a function that accepts plotting parameters, which it *is* for `ds.proj` (hence why projection plots work) but not for `ds.Particle`. I don't have enough knowledge of the internals of yt to sort this out, but I'd be willing to have a go if someone can point me in the right direction. 

Here:
- `data_source` refers to a `yt.data_objects.construction_data_containers` object, and
- `ds` refers to a `yt.frontends.X.data_structures` object.

I have tried looking for the definition of `_type_name`, but I can't seem to find anything helpful. So far, I have tracked down the `_type_name = Particle` to `yt.visualization.particle_plots.py`.

**Comment by ngoldbaum** [comment]
The `_type_name` should always be a string, I think. It's define at class level for each of the yt data objects (see e.g. [here](https://github.com/yt-project/yt/blob/master/yt/data_objects/selection_data_containers.py#L617) for the `region` data object or [here](https://github.com/yt-project/yt/blob/master/yt/data_objects/construction_data_containers.py#L221) for the projection data object.

I'm a little confused by your statement that yt expects `ds._type_name` to be a function. Where is that happening?

**Comment by JBorrow** [comment]
If you look [here](https://github.com/yt-project/yt/blob/master/yt/visualization/plot_container.py#L325) it seems to me at least that a function with the name `old_object._type_name` is expected to exist as part of `new_object`.

**Comment by ngoldbaum** [comment]
Ah, I see what's happening. So in that code you're linking to, `new_ds` is a dataset, (e.g. an instance of `GadgetDataset`, for example. Datasets have data objects hanging off of them. For example, one can do `ds.proj(axis, field_name)` to create a projection data object. So that code is basically creating a new data object to create the plot with.

Particle plots don't work quite the same way as other yt plot types. Projection plots get the data to plot from a projection data object. Similarly, slice plots get their data to plot from a slice data object (`ds.slice`). For `ParticleProjectionPlot`, it turns out that the underlying data object is a `ParticleAxisAlignedDummyDataSource`, (see [here](https://github.com/yt-project/yt/blob/master/yt/visualization/particle_plots.py#L241) and [here](https://github.com/yt-project/yt/blob/master/yt/visualization/particle_plots.py#L34) for the definition of `ParticleAxisAlignedDummyDataSource`) and for `ParticlePhasePlot`, the underlying data object is a 3D data container (so I believe that will work fine with `_switch_ds`. This is all a symptom of the way `ParticleProjectionPlot` is written, making use of this special dummy data source, and that's breaking some assumptions that `_switch_ds` is making about the relationship between yt plots and yt data objects that all the other plots obey. I'm not sure offhand if there's a refactoring we could do to make this cleaner and avoid adding more hacks.

However, the easiest solution would definitely be to add a new hack. In particular, you could add a special case to `_switch_ds`, something along the lines of this:

```
if name == 'particle':
    new_object = ParticleAxisAlignedDummyDataSource(**kwargs)
else:
    new_object = getattr(new_ds, name)(**kwargs)
````

Finally, sorry for not taking a closer look at the issue after you reported it. I intended to but it slipped my mind. I take bug reports seriously, especially from people like you who have shown a willingness to contribute and I shouldn't have waited for you to poke at the issue before looking closely at it. Anyway, I hope my explanation is helpful. If you'd like, it would be awesome if you could make a pull request with a fix. If you don't feel comfortable doing that I'd be happy to look more closely at this today or tomorrow.

**Comment by JBorrow** [comment]
No worries - I just assumed you were busy! Thanks for the insight into the way the plots work.

I'll get to submitting a PR for this soon; at the moment I'm getting an odd error when importing from `ParticleAxisAlignedDummyDataSource` from `yt.visualization.particle_plots`. You can get the same error when running `yt/visualization/particle_plots.py` as it's to do with imports:

```
Traceback (most recent call last):
  File "../yt/yt/visualization/particle_plots.py", line 18, in <module>
    from yt.visualization.fixed_resolution import \
  File "/Users/josh/Documents/yt/yt/__init__.py", line 75, in <module>
    from yt.data_objects.api import \
  File "/Users/josh/Documents/yt/yt/data_objects/api.py", line 22, in <module>
    from .static_output import \
  File "/Users/josh/Documents/yt/yt/data_objects/static_output.py", line 71, in <module>
    from yt.data_objects.region_expression import \
  File "/Users/josh/Documents/yt/yt/data_objects/region_expression.py", line 20, in <module>
    from yt.visualization.line_plot import LineBuffer
  File "/Users/josh/Documents/yt/yt/visualization/line_plot.py", line 28, in <module>
    from yt.visualization.plot_container import \
  File "/Users/josh/Documents/yt/yt/visualization/plot_container.py", line 50, in <module>
    from yt.visualization.particle_plots import \
  File "/Users/josh/Documents/yt/yt/visualization/particle_plots.py", line 18, in <module>
    from yt.visualization.fixed_resolution import \
  File "/Users/josh/Documents/yt/yt/visualization/fixed_resolution.py", line 23, in <module>
    from .volume_rendering.api import off_axis_projection
  File "/Users/josh/Documents/yt/yt/visualization/volume_rendering/api.py", line 23, in <module>
    from .camera import Camera
  File "/Users/josh/Documents/yt/yt/visualization/volume_rendering/camera.py", line 21, in <module>
    from .utils import data_source_or_all
  File "/Users/josh/Documents/yt/yt/visualization/volume_rendering/utils.py", line 4, in <module>
    from yt.data_objects.static_output import Dataset
ImportError: cannot import name 'Dataset'
```

**Comment by ngoldbaum** [comment]
I’d guess it’s due to a cyclic import. It will probably work if you put the import inside of the `_switch_ds` function.

**Comment by ngoldbaum** [comment]
Ckised by #1594.
