### ISSUE TITLE
yt fails to load `openPMD` files when either no fields or no particles are present

### ISSUE THREAD

**Issue by RemiLehe** [yt-project/yt#1626]
### Bug report

**Bug summary**

yt fails to load `openPMD` files when either no fields or no particles are present. (It works fine when both particles and fields are present.)

**Code for reproduction**

Here are two zip files which contain valid openPMD files that either have no particles or no fields.
[no_fields.zip](https://github.com/yt-project/yt/files/1476509/no_fields.zip)
[no_particles.zip](https://github.com/yt-project/yt/files/1476510/no_particles.zip)

After unzipping them, the following code snippets lead to errors
```python
import yt
yt.load('./no_particles/data00000400.h5')
```
```python
import yt
yt.load('./no_fields/data00000400.h5')
```

**Actual outcome**

Here is the output, i.e. in the case with no particles:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-6-606762cc9ee1> in <module>()
----> 1 yt.load('./example-ptcl/hdf5/data00000400.h5')

~/miniconda3/lib/python3.6/site-packages/yt/convenience.py in load(*args, **kwargs)
     84     candidates = find_lowest_subclasses(candidates)
     85     if len(candidates) == 1:
---> 86         return candidates[0](*args, **kwargs)
     87     if len(candidates) == 0:
     88         if ytcfg.get("yt", "enzo_db") != '' \

~/miniconda3/lib/python3.6/site-packages/yt/frontends/open_pmd/data_structures.py in __init__(self, filename, dataset_type, storage_filename, units_override, unit_system, **kwargs)
    385         self.storage_filename = storage_filename
    386         self.fluid_types += ("openPMD",)
--> 387         particles = tuple(str(c) for c in self._handle[self.base_path + self.particles_path].keys())
    388         if len(particles) > 1:
    389             # Only use on-disk particle names if there is more than one species

~/miniconda3/lib/python3.6/site-packages/yt/utilities/file_handler.py in __getitem__(self, key)
     43 
     44     def __getitem__(self, key):
---> 45         return self.handle[key]
     46 
     47     def __contains__(self, item):

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/Users/ilan/minonda/conda-bld/h5py_1496887972496/work/h5py/_objects.c:2846)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/Users/ilan/minonda/conda-bld/h5py_1496887972496/work/h5py/_objects.c:2804)()

~/miniconda3/lib/python3.6/site-packages/h5py/_hl/group.py in __getitem__(self, name)
    167                 raise ValueError("Invalid HDF5 object reference")
    168         else:
--> 169             oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
    170 
    171         otype = h5i.get_type(oid)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/Users/ilan/minonda/conda-bld/h5py_1496887972496/work/h5py/_objects.c:2846)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/Users/ilan/minonda/conda-bld/h5py_1496887972496/work/h5py/_objects.c:2804)()

h5py/h5o.pyx in h5py.h5o.open (/Users/ilan/minonda/conda-bld/h5py_1496887972496/work/h5py/h5o.c:3740)()

KeyError: "Unable to open object (Object 'particles' doesn't exist)"
```

**Expected outcome**

`yt` should be able to access the existing data (either particle-only or field-only data) in the same way as if both particles and fields where in the same file.

**Version Information**

  * Operating System: MacOSX
  * Python Version: 3.6
  * yt version: 3.4 (installed with `conda install -c conda-forge yt`)

**Comment by RemiLehe** [comment]
Pinging @atmyers @ax3l @C0nsultant as they might be interested.

**Comment by ngoldbaum** [comment]
I guess the first thing I'd do is add a check before this line:

https://github.com/yt-project/yt/blob/38b79c094ca9b7c45cc3c5555d22cc630f20cba4/yt/frontends/open_pmd/data_structures.py#L387

To see if the dataset actually exists in the HDF5 file.

**Comment by C0nsultant** [comment]
Author of the openPMD frontend here.

The backend was implemented under the assupmtion that the paths pointed to by openPMDs metadata correspond to existing locations in the file.
`meshesPath` and `particlesPath` are required by design. Whether the locations behind these attributes must exist is not stated explicitly. 
This was assumed to be the case during development: Even if a simulation contains no particles/meshes, the folder indicated by `meshesPath`/`particlesPath` exists and is empty.

Whether these files are valid openPMD is up to interpretation (IMO they are not).
@ax3l in a discussion at [the standard](https://github.com/openPMD/openPMD-standard/issues/143#issuecomment-344645198) suggests they are.
If that is the consensus, I will modify the yt frontend accordingly.

**Comment by ax3l** [comment]
> Whether the locations behind these attributes must exist is not stated explicitly.

yes, that's a sloppyness we did in the `1.0.0` version and are about to fix it in `1.0.1` https://github.com/openPMD/openPMD-standard/issues/143

Our plan is: for the revision (clarification) in `1.0.1` (and the current implementation) we just keep `meshesPath` & `particlesPath` as required attributes, but silently assume there a no meshes (or no particles) if the path is not existent. Since that is sloppy, we should throw a DEBUG or INFO message in such a case (but *not* a warning).

In the `2.X` release we will make the attributes `meshesPath` and `particlesPath` optional. If set, the pathes they point to *must* exist, otherwise it's a format error.

**Comment by C0nsultant** [comment]
> for the revision (clarification) in 1.0.1 [...]

Which, to be fully backward compatible, requires my assumption to not hold under `1.0.0`.

> In the 2.X release [...]

Enforcing these contraints in the frontend is trivial once a major new version without backward compatability is released.

I'll be working on it.

**Comment by ax3l** [comment]
> Which, to be fully backward compatible, requires my assumption to not hold under 1.0.0.

Yes, we just define for 1.0.1 readers a previously undefined behavior. Reading 1.0.0 files will still be compatible, which is what we strive for with this minimal-invasive change.
