### ISSUE TITLE
Make it clearer how to load a multifile gadget dataset

### ISSUE THREAD

**Issue by ngoldbaum** [yt-project/yt#1689]
For large Gadget simulations, the output is spread over multiple files on disk. Currently to load all of these files as a single dataset, a user needs to know that they should load only *one* of those files. For example:

```
goldbaum at ROUS in ~/Documents/test
○ ls snapshot_033
snap_033.0.hdf5               snap_033.4.hdf5
snap_033.0.hdf5.index7_5.ewah snap_033.5.hdf5
snap_033.1.hdf5               snap_033.6.hdf5
snap_033.2.hdf5               snap_033.7.hdf5
snap_033.3.hdf5

goldbaum at ROUS in ~/Documents/test
○ yt load snapshot_033/snap_033.0.hdf5
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: ds.file_count
Out[1]: 8
```

Confusingly, if you pass a glob pattern, you get back a DatasetSeries:

```
In [2]: ds = yt.load('snapshot_033/snap_033.*.hdf5')

In [3]: type(ds)
Out[3]: yt.data_objects.time_series.DatasetSeries
```

It would be nice if we could short-circuit the logic that says "this is a glob pattern, therefore it must be a DatasetSeries" to also check for output types like Gadget that allow a single dataset to span multiple files.

We should also make it clearer in the documentation that the canonical way to load multi-file gadget outputs is to load the 0th file.

**Comment by ngoldbaum** [comment]
@munkm volunteered to look at this

**Comment by virajpandya** [comment]
Quick comment: I noticed that this works as intended (when I load the 0th hdf5 file of a multi-block Gizmo/Gadget snapshot, the remaining ones also get automatically read in). However, if I didn't have the other blocks on my disk, then yt still tries to read the other blocks in and this leads to an error (because it can't find the other block files).

Here's an example failure from when I try to read in the 8th and final block of a snapshot called snapshot_170.7.hdf5 (the other blocks 0-6 are not on my disk): 

`IOError: Unable to open file (Unable to open file: name = 'snapshot_170.0.hdf5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)`

Is this intended? Or is there an argument for yt.load() that would prevent the auto-attempt to read other blocks of a Gizmo/Gadget snapshot? 

P.S. This seems related to this open ticket: https://github.com/yt-project/yt/issues/1332

**Comment by ngoldbaum** [comment]
No, we don't support that. If you want to load in a subset of the data use the `bbox` keyword argument to `yt.load()`. If you make the bounding box smaller than the simulation volume, yt will only load in particles that are inside the bounding box.
