### ISSUE TITLE
Anaconda installation issues 

### ISSUE THREAD

**Issue by jsmidt** [yt-project/yt#1716]
There are two issues I have seen [trying to install with anaconda](http://yt-project.org/doc/installing.html#installing-yt-using-anaconda):

1. First, ```conda install -c http://use.yt/with_conda/ -c conda-forge yt``` does not seem to work because http://use.yt/with_conda appears to be down.  [See here](https://imgur.com/a/CLOfO)

2. Second, if you type ```conda install yt``` it installs an old version of yt: 3.3.5.  I realize that the documentation says to add ```-c conda-forge``` but two things.  

      * First, conda-forge has some unique versions of python packages that differ from the vanilla conda install such that one of the conda-forge packages broke my other python code.  

      * Second, at one time it seems as those someone was able to update yt for the standard conda channel (hence up through 3.3.5 exists), so why stop?  That way you can stick with the standard conda packages that 'just work' with everything else.

Thanks.

**Comment by ngoldbaum** [comment]
Thanks for the report about http://use.yt/with_conda, that's there for installing some additional dependencies that aren't currently packaged on conda-forge. We currently recommend installing yt from conda-forge because we can control when those packages get updated.

We have no control over when packages on the default channel get updated. I actually pinged them a week ago to update the package:

https://groups.google.com/a/continuum.io/d/msg/anaconda/cXS4k8SL_g0/n_e9EGwZAwAJ

If you can't use conda-forge, it may be easiest to either install yt into your conda environment using pip (there are yt wheels on pypi) or to build yt from source.

**Comment by jsmidt** [comment]
Thank you.

**Comment by ngoldbaum** [comment]
I've opened #1718 to track the issues with use.yt/with_conda. I'm closing this issue since the questions in the original issue were answered.

**Comment by ngoldbaum** [comment]
It looks like they have conda packages for 3.4.1 in the main channel now.
