### ISSUE TITLE
PhasePlot broken for `sampling_type='local'` fields

### ISSUE THREAD

**Issue by chummels** [yt-project/yt#1754]
### Bug report

**Bug summary**

Trying to create a `PhasePlot` with a `sampling_type='local'` does not work.  Under the demeshening, most fields are meant to have `sampling_type='local'` and not `'particle'` or `'grid'`, so this effectively breaks the functionality of `PhasePlot` with any new fields (and specifically, for any new fields created by `Trident`).  This bug was originally identified by Iryna Butsky.

**Code for reproduction**

```python
import yt
ds = yt.load('FIRE_M12i_ref11/snapshot_600.hdf5')
def _dummy(field, data):
    return data[('gas', 'density')]
ds.add_field(('dummy'), function=_dummy, sampling_type="local", units='g/cm**3')
ad = ds.all_data()
phase = yt.PhasePlot(ad, "density", "temperature", ["dummy"], weight_field=None)
phase.save()
```

**Actual outcome**

Errors out with traceback:

```
Traceback (most recent call last):
  File "test_phase.py", line 7, in <module>
    phase = yt.PhasePlot(ad, "density", "temperature", ["dummy"], weight_field=None)
  File "/Users/chummels/src/yt-conda/src/yt-git/yt/visualization/profile_plotter.py", line 804, in __init__
    fractional=fractional)
  File "/Users/chummels/src/yt-conda/src/yt-git/yt/data_objects/profiles.py", line 988, in create_profile
    bin_fields, data_source._determine_fields(fields), wf, is_pfield)
yt.utilities.exceptions.YTIllDefinedProfile:
Cannot create a profile object that mixes particle and mesh fields.

Received the following bin_fields:

   [('PartType0', 'density'), ('PartType0', 'temperature')], particle_type = [True, True]

Profile fields:

   ('gas', 'dummy'), particle_type = False
```

**Comment by chummels** [comment]
PR fix here:

https://github.com/ngoldbaum/yt/pull/1

**Comment by ngoldbaum** [comment]
So part of the issue here is that "density" corresponds to more than one field tuple (in this case both `('gas', 'density')` and `('PartType0', 'density')`). One thing I'd like to do in yt-4.0 is make it so using an ambiguous string field name raises an error, with the goal of moving people to use either field tuples all the time or e.g. use `ds.fields.gas.density` to force people to specify the field type. I suspect this would work right now if you created the PhasePlot like this:

```
phase = yt.PhasePlot(ad, ('gas', "density"), ('gas', "temperature"), ["dummy"], weight_field=None)
```

Anyway, you're probably also right that mixing two particle fields with a local field is OK, and I think a fix that did that kind of check would be welcome.

I closed your PR because just deleting the check entirely will weaken our sanity checking for AMR data. This fix is to improve the sanity checking, not just ignore it.

**Comment by chummels** [comment]
But why should we have a check on mixing particle and non-particle fields when the idea is that in the demeshening such fields are treated equally?

**Comment by chummels** [comment]
In Trident, you replaced all of the `sampling_type='particle'` with `sampling_type='local'`, or this wouldn't have been a problem.  But it seems to me that the hangup is that fields are still being marked as `sampling_type='particle'` when yt reads them in, no?

**Comment by ngoldbaum** [comment]
I/O fields are read in as particle fields, that's correct.

The issue is that the check you're running into is not smart enough to understand the changes we've made in the demeshening. It's ok to plot two particle fields and a local field, since the local field will resolve to a particle field for particle data.

It's true that there isn't an easy way right now to see whether the "local" field type is really a mesh field, particle field, or something else. The trouble you're running into indicates that we might want to add such a capability and then expand the logic that triggers the error message to handle local fields.

It's not OK to plot a local field and a particle field for AMR data. Even after the demeshening, yt needs to support AMR data, where the check that's causing trouble here is still needed so we can't just outright delete it.

**Comment by ngoldbaum** [comment]
That said, if you're just working with SPH data, your hack is fine.

I've been travelling this week and haven't had time to look at the issues you reported. I'm planning to spend some time next week doing so.

Thank you for reporting these issues and testing the demeshening, I really appreciate it.

**Comment by chummels** [comment]
Ahh, I understand.  I didn't realize the issue with mixing AMR and particle fields was still present.  Thanks for the full explanation!

No worries on the delays.  I just thought I had a quick solution so I'd PR it, but I understand now why my fix was insufficient.  I'll have an additional PR shortly that I think will work and remain safe for the situation you described above.  Thanks for the help!

**Comment by ngoldbaum** [comment]
I managed to reproduce this on a smaller in-memory dataset:

```
import yt
from yt.testing import fake_sph_orientation_ds
ds = fake_sph_orientation_ds()
plot = yt.PhasePlot(ds.all_data(), 'density', 'temperature', 'kinetic_energy', weight_field=None)
```

**Comment by ngoldbaum** [comment]
Just pushed a fix, see https://github.com/ngoldbaum/yt/commit/fad57c97e1a7c938501f0fe4a821f957f192c95e. If the tests fail I'll push more commits to fix that :)

**Comment by chummels** [comment]
This fixes the issue entirely.  Thank you for coming up with a more sophisticated solution than my "rip out the check" method. :)
