### ISSUE TITLE
Issues with plotting density profile for AMR data

### ISSUE THREAD

**Issue by annarosen84** [yt-project/yt#1773]
### Bug report

**Bug summary**

When creating a density profile plot as a function of radius for several files I get that the first one is correct (AMR structure is simple) but when I compute the same profile for later data files, when the AMR structure is more completed

**Code for reproduction**
```python
    accumalate = False
    proField = 'cloud_density'
    weight = 'cell_mass'
    sp = ds.sphere(ds.domain_center, (0.2, "pc"))

    # Bin up the data from the sphere into a radial profile

    rp = yt.create_profile(sp, 'radius', [proField],accumulation = accumalate,
                           units = {'radius': 'au'}, weight_field=weight,
                           logs = {'radius': False})

    sp = ds.sphere(ds.domain_center, (40e3, "au"))
    mtot = (sp['cell_volume']*sp['cloud_density']).sum()/MSUN
    #mtot = sp.quantities.total_quantity('cloud_density')/1.989e33
    print(mtot)
    mtotb = mtot.v+smax
    print(str(mtot) + ', ' + str(smax) +  ', ' + str(mtotb))
    # Plot the density as a log-log plot using the default settings
    if i ==0:
        if not(accumalate):
            dens_plot = ax.loglog(rp.x.value/1e3, rp[proField].value, 
                                  color='SlateGray', lw=2 , alpha=0.75, ls= '--')
        else:
            dens_plot = ax.plot(rp.x.value/1e3, rp[proField].value,
                                  color='SlateGray', lw=2 , alpha=0.75, ls= '--')
    else:
        if not(accumalate):
            dens_plot = ax.loglog(rp.x.value/1e3, rp[proField].value,
                                  color=colors[i-1], label=lab, lw=2 , ls = ls[i-1], alpha=0.75)
        else:
            dens_plot = ax.plot(rp.x.value/1e3, rp[proField].value,
                                  color=colors[i-1], label=lab, lw=2 , ls = ls[i-1], alpha=0.75)
    x=rp.x.value*AUCM
    y = 4*math.pi*x**2.*rp[proField].value
    x=rp.x.value*AUCM
    y = 4*math.pi*x**2.*rp[proField].value
    Mtotint= np.trapz(y,x)
    print('Total gas mass integral = ' + str(Mtotint/MSUN))
```

**Actual outcome**

Attached is a screenshot showing the problem. The density profiles at later times (blue and pink lines) should be below the gray line (initial density distribution). This is a star formation simulaiton so mass is being added to the star and not the gas (gas is losing mass).

<img width="500" alt="screenshot 2018-05-01 20 06 52" src="https://user-images.githubusercontent.com/5092633/39499367-67634894-4d7b-11e8-96ea-dd88cb92669c.png">

```
(all #s are in units Msun)
for initial data file:
150.411289660549 code_length**3*g/cm**3
150.411289660549 code_length**3*g/cm**3, 0, 150.411289660549 (total gas mass in sp, stellar mass, sum)
Total gas mass integral = 152.04406171403144 (integrated value)

for later snapshot:
116.93007113240911 code_length**3*g/cm**3
116.93007113240911 code_length**3*g/cm**3, 31.1390511771749, 148.069122309584
Total gas mass integral = 1421.144015858941
```

**Expected outcome**

**Version Information**

  * Operating System: Linux
  * Python Version: 3.6
  * yt version: 3.4
  * Other Libraries (if applicable): 

I installed from conda.

**Comment by ngoldbaum** [comment]
What’s `cloud_density`? It looks like you are using a weight field, so that’s not the issue.

Is there any chance you can share the data files you used to run the script? If they’re not too huge (~ 5 GB) and you don’t mind sharing them publicly you can share them with `yt upload file.tar.gz`. If they’re private or really enormous we can try debugging remotely, although that might get tedious if we need to do a lot of back and forth.

**Comment by ngoldbaum** [comment]
Also you said you’re running yt 3.4, is that 3.4.0? If so can you try with 3.4.1 or even better the latest version of yt on the git master branch.

**Comment by annarosen84** [comment]
Hey nathan,

Thanks for the quick response. I'm using the latest stable version, which I
just reinstalled yesterday. For some reason, it took me a long time to get
it installed properly on hyades so I'd rather not change to the development
version until June (I'll be traveling from mid-May to early June for
conferences). But I can switch to the development version after my trip.

cloud_density is a field that i defined that traces the core density
(ignores the ambient medium), density works just the same. I was seeing the
same problem with both.

I uploaded the files, here are the links:

orion2.ini
http://use.yt/upload/58e0b816

data.0000 (initial file)
http://use.yt/upload/7da3c258

http://use.yt/upload/f82ef63e

data.0220
http://use.yt/upload/e2e93d57

http://use.yt/upload/d091a786

data.0513
http://use.yt/upload/df769e07

http://use.yt/upload/c4e4bedd

Thanks for your help with this!

-Anna

**Comment by ngoldbaum** [comment]
Ok, I'll try to take a look at this soon.

> For some reason, it took me a long time to get it installed properly on hyades

Any chance you can elaborate on this in a separate issue? Was it something broken on our end?

**Comment by ngoldbaum** [comment]
I wasn't able to run the script Anna pasted in the original issue because there are some undefined variables. I ended up adapting it though and I think I understand what's going on. Take a look at this script:

```python
import glob
import yt
from matplotlib import pyplot as plt

ds_list = glob.glob('*.hdf5')
fig, ax = plt.subplots()

for dsfn in sorted(ds_list):
    print(dsfn)
    ds = yt.load(dsfn)
    accumalate = False
    proField = 'cell_mass'
    weight = None
    dd = ds.all_data()

    # Bin up the data from the sphere into a radial profile

    rp = yt.create_profile(dd, 'radius', [proField], accumulation=accumalate,
                           units={'radius': 'au'}, weight_field=weight,
                           logs={'radius': False}, n_bins=512)

    mtot = (dd['cell_mass']).sum()

    print('Total gas mass:', mtot.to('msun'))

    # Plot the density as a log-log plot using the default settings

    dens_plot = ax.loglog(rp.x, rp[proField], lw=2, label=dsfn)

    print('Total gas mass profile:', rp[proField].sum().to('Msun'))

ax.legend()
plt.savefig('plot.png')
```

Here I'm making a profile of mass as a function of radius. I've also set weight_field=None, which makes the profile object calculate a sum rather than an average. By doing it this way I'm directly comparing both the mass profile and and the summed mass across the AMR mesh. Here you can clearly see in the plot that the mass is draining onto the sink particle:

![plot](https://user-images.githubusercontent.com/3126246/39607583-67df0e8e-4f01-11e8-8c95-2e47d07892dc.png)

(the y axis is mass in grams, the x axis is radius in AU)

When I run the script I get exact agreement between the mass calculated with the data object and the profile, and that mass goes down with time:

```
data.0000.3d.hdf5
Total gas mass: 161.17512893917245 msun
Total gas mass profile: 161.17512893917154 Msun
data.0220.3d.hdf5
Total gas mass: 152.1765174454687 msun
Total gas mass profile: 152.1765174454686 Msun
data.0513.3d.hdf5
Total gas mass: 143.01068966671983 msun
Total gas mass profile: 143.0106896667198 Msun
```

In your script you're calculating the mass-weighted density profile. I'm pretty sure that's the issue. Since it's a mass-weighted average, you're emphasizing the influence of AMR cells that have more mass in them. This means the profile overestimates the true bulk average density in that radial bin. Then, when you use this weighted estimate to again estimate the cloud mass using `np.trapz`, you get an overestimate.

Another way to see this is to change the weight field to `cell_volume`. In this case you're emphasizing the relatively underdense regions of the simulation, and the estimated mass goes *down* with time.

Here's another version of the script, but tweaked to profile the density field as Anna did in the original issue. 

```python
import glob
import yt
import numpy as np
from matplotlib import pyplot as plt

ds_list = glob.glob('*.hdf5')
fig, ax = plt.subplots()

for dsfn in sorted(ds_list):
    print(dsfn)
    ds = yt.load(dsfn)
    accumalate = False
    proField = 'density'
    weight = 'cell_volume'
    dd = ds.all_data()

    # Bin up the data from the sphere into a radial profile

    rp = yt.create_profile(dd, 'radius', [proField], accumulation=accumalate,
                           units={'radius': 'au'}, weight_field=weight,
                           logs={'radius': False}, n_bins=512)

    mtot = (dd['cell_mass']).sum()

    print('Total gas mass:', mtot.to('msun'))

    # Plot the density as a log-log plot using the default settings

    dens_plot = ax.loglog(rp.x, rp[proField], lw=2, label=dsfn)

    x = rp.x
    y = 4*np.pi*x**2.*rp[proField]

    Mtotint = np.trapz(y, x)
    print('Total gas mass integral = ' + str(Mtotint.to('msun')))

ax.legend()
plt.savefig('plot.png')
```

Here's the output of this script with `weight=cell_volume`:

![plot](https://user-images.githubusercontent.com/3126246/39607842-0a12dbbc-4f03-11e8-8989-e0e10103baf2.png)

```
data.0000.3d.hdf5
Total gas mass: 161.17512893917245 msun
Total gas mass integral = 178.3515685870288 msun
data.0220.3d.hdf5
Total gas mass: 152.1765174454687 msun
Total gas mass integral = 169.4845429198556 msun
data.0513.3d.hdf5
Total gas mass: 143.01068966671983 msun
Total gas mass integral = 160.17372952636958 msun
```

And here's the output with `weight=cell_mass`:

![plot](https://user-images.githubusercontent.com/3126246/39607919-91215688-4f03-11e8-9975-56360e837a71.png)

```
ata.0000.3d.hdf5
Total gas mass: 161.17512893917245 msun
Total gas mass integral = 178.54052509136514 msun
data.0220.3d.hdf5
Total gas mass: 152.1765174454687 msun
Total gas mass integral = 775.1654174786845 msun
data.0513.3d.hdf5
Total gas mass: 143.01068966671983 msun
Total gas mass integral = 1144.9159735927167 msun
```

I think what's driving this in your data is that the mass-weighted average is picking up overdensities at large radii and magnifying their influence in the final estimated cloud mass. Since they're at large radii, they contribute a lot to the estimate.

The only thing I don't understand is why the `cell_volume` weighted average estimate for the cloud mass still overestimates the true cloud mass at all times. I guess the data not spherically symmetric in a systematic manner that gets picked up throughout the simulation?

Anyway, do you agree with my analysis?

I noticed in your original script that you were stripping units a lot. These days the unit system and matplotlib play pretty nicely together. I'd encourage you to use yt's unit system to do unit conversions instead rather than using floating point constants. That might make it easier to see what's happening :)

**Comment by ngoldbaum** [comment]
> I guess the data not spherically symmetric in a systematic manner that gets picked up throughout the simulation?

Actually, I think this is probably because of the binning. It seems to converge to the actual mass in the box when I use more bins, until eventually there are bins with zeros in them and the `trapz`-based estimate stops making sense.

**Comment by annarosen84** [comment]
Hey nathan,

Thanks for looking into this! Following what you said I got it to work.
When I originally started working on this plot I did not set a weight
field. I assumed the weight field was set to None by default, but I'm
guessing now that the weight field is set to cell_mass by default. However,
this wasn't in the documentation :

weight_field : str or tuple field identifier
The weight field for computing weighted average for the profile
    values.  If None, the profile values are sums of the data in
    each bin.

I didn't look at the code because for some reason on Hyades I can't clone
the repo.

Thanks,

Anna

**Comment by ngoldbaum** [comment]
The default's always been `cell_mass`, FWIW. You don't need to clone the repo to see the default value of a variable:

http://yt-project.org/doc/reference/api/yt.data_objects.profiles.html#yt.data_objects.profiles.create_profile

You can see in the signature that the default is `'cell_mass'`. You're correct it's not listed in the main body of the docstring though. That's probably worth adding.

> I didn't look at the code because for some reason on Hyades I can't clone the repo.

That's odd. I'm surprised that cloning a git repo from github doesn't work. Unfortunately I no longer have a hyades account so I can't help you debug there. You may want to chat with Brant though, since being able to see github is very important.

Since this has been resolved I'm closing the issue.
