### ISSUE TITLE
 AttributeError: 'Clump' object has no attribute 'clump_info'

### ISSUE THREAD

**Issue by astro313** [yt-project/yt#1898]
Hi,

I am using the yt clumpfinder, and I tried to pickle the Clump object after running `find_clump()`, but got an error when I pickled: 
```
master_clump = Clump(dd, field)
find_clumps(master_clump, c_min, c_max, step)
leaf5 = get_lowest_clumps(master_clump)
pickle.dump(leaf5, open("blah.p", "wb"))
```

Error: 
```
File "/mnt/home/daisyleung/Downloads/yt-conda/lib/python2.7/site-packages/yt/analysis_modules/level_sets/clump_handling.py", line 404, in __reduce__ self.valid, self.children, self.data, self.clump_info, 
AttributeError: 'Clump' object has no attribute 'clump_info'
```

  * Python Version: 2.7
  * yt version: 3.4.1

**Comment by brittonsmith** [comment]
Hi there!

Can I recommend you try using the `save_as_dataset` command instead of the pickle method? This function has been designed to save the clump structure to a reloadable format.

For example:
```
fn = master_clump.save_as_dataset(fields=["density", "particle_mass"])
clumps_ds = ds.load(fn)
leaves = clumps_ds.leaves
```

You can find more information on using this method in [this recipe](http://yt-project.org/docs/dev/cookbook/constructing_data_objects.html#cookbook-find-clumps).

**Comment by ngoldbaum** [comment]
Also here: http://yt-project.org/doc/analyzing/analysis_modules/clump_finding.html#saving-and-reloading-clump-data

That said, we have `__setstate__` method and we should probably fix it (and add tests) now that it's broken.
