### ISSUE TITLE
Where is LightCone going to end up?

### ISSUE THREAD

**Issue by jzuhone** [yt-project/yt#1930]
`LightRay` has been ported to `trident`, but where is `LightCone` going? pyXSIM subclasses `LightCone`, but now we get a warning message when we import it:

from `yt/analysis_modules/cosmological_observation/light_ray/api.py`:

```python
issue_deprecation_warning(
    "Development of the LightRay module has been moved to the Trident "
    "package. This version is deprecated and will be removed from yt "
    "in a future release. See https://github.com/trident-project/trident "
    "for further information.")
```

Where it goes is not a big deal to me, but I was curious as to any plans for further implementation.

ping @brittonsmith @chummels

**Comment by jzuhone** [comment]
Note that the fact I see this deprecation warning is likely a side effect of the fact that I am importing `LightCone` from the base-level `cosmological_observation` API import. But I think the question still stands.

**Comment by ngoldbaum** [comment]
https://github.com/yt-project/yt_astro_analysis ?

**Comment by brittonsmith** [comment]
My thought was for `LightCone` to be a part of `yt_astro_analysis`.  That and `cosmology_splice` have already been added to that codebase.  We are pretty close to a stable release for `yt_astro_analysis`.  I think all of the blocking bugs have been fixed in the yt codebase and we just need to port them over and do the packaging.

**Comment by jzuhone** [comment]
Ok, I figured this might be the case, but thanks for the clarification! Sounds good to me.
