### ISSUE TITLE
How to recompile frontend yt in conda

### ISSUE THREAD

**Issue by ricardovolert** [yt-project/yt#2039]
good evening everyone,

I have a conda installation to access yt, however, I needed to change the folder parameter: "home/user/Documents/yt-project/yt-conda/lib/python3.6/site-packages/yt/frontends/gadget/fields.py"

currently:

`                   # Assume zero ionization
                    mu = 4.0 / (3.0 * x_H + 1.0)`

change to:

`                    # Assume full ionization
                    mu = 4.0 / (5.0 * x_H + 3.0)`

I would like to know how to proceed to put to work with these new parameters since it seems that nothing has changed in my data. Can you help me?

Thanks!

**Comment by ngoldbaum** [comment]
It sounds like you’re trying to make a patch to yt for some reason? You probably judt want to buold yt from source using the git repository. It’s not clear to me why you want to make this modification, but if you think the code that’s
in yt right now is incorrect then you will be in a much better position to make a pull request with a fix if you bulld yt from source rather than try to modify a version installed from conda.

Closing this because it’s a question about installing yt rather than a bug per se.
