### ISSUE TITLE
Velocity vectors do not get converted to cylindrical components in 3D cylindrical geo

### ISSUE THREAD

**Issue by jisuoqing** [yt-project/yt#2103]
### Bug report

**Bug summary**

In 3d cylindrical coordinates, velocity vectors do not get converted to (r, theta, z) components (but magnetic field vectors do).

**Code for reproduction**

Datafile: [https://www.dropbox.com/s/jmstyqittx8ubz2/cyl3d.hdf5?dl=0](https://www.dropbox.com/s/jmstyqittx8ubz2/cyl3d.hdf5?dl=0)

```python
import yt
  
ds = yt.load("cyl3d.hdf5")
print(ds.derived_field_list)
print(ds.all_data()["velocity_magnitude"][0])
```

**Comment by ngoldbaum** [comment]
So the issue here is that there's a bunch of logic in `yt/fields/magnetic_field.py` that delegates on the geometry of the dataset to set up a different set of fields for cylindrical, spherical, and cartesian data. There's no corresponding code for the velocity fields. Someone would need to go in and the necessary logic to ensure that gets set up correctly for curvilinear data. I guess we should probably extract the special logic for magnetic fields and make it happen in general for all vector fields in `yt/fields/vector_operations.py`.

**Comment by ngoldbaum** [comment]
To start, I think we need something like `setup_magnetic_field_aliases` for velocity fields (or even better an arbitrary fluid vector field), that sets up the aliases in the flash frontend from e.g. `magz` to `magnetic_field_theta` for this dataset.
