### ISSUE TITLE
Discussion: make Dataset an abstract class ?

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#2426]
about frontends development in general: the Dataset class, as it stands, is an abstract class as
some of its code relies on unimplemented methods. When we wrote the AMRVAC frontend with @n-claes, especially as we were getting started, it was quite confusing how there wasn't a really explicit edge between what has to be there for the child class `<YourFrontend>Dataset` to work, and what can be left unimplemented (at least a first). Taking inspiration from existing frontends also adds to the confusion in some ways, because most frontends will add code-specific methods, so as a newcomer you have to jump from one to the other in order to grasp which is which.

I was thinking that it could help future contributors to make Dataset an actual abstract class by inheriting from `abc.ABC` . As the exact syntax for doing this seems different in python 2, maybe that could be a change reserved for yt 4.0.

I'm not aware of any good reason why not to do this, though there might very well be. Any input ?

**Comment by matthewturk** [comment]
I strongly support this and would like to participate.

**Comment by neutrinoceros** [comment]
side note: we do have "notes" about this as  _comments_ in the `AMRVACDataset` class, where each method is labelled as required or frontend-specific, which could help.

I do not expect the change itself to be difficult, especially if we give up on python 2.

**Comment by cphyc** [comment]
That would be a very valuable improvement! I had similar issues when working on the RAMSES frontend or the AdaptaHOP one.

**Comment by neutrinoceros** [comment]
So unless I'm mistaken, the most fundamental change required here would be this:

```python
# current
class RegisteredDataset(type):

# proposed
import abc
class RegisteredDataset(abc.ABCMeta):
```

then it's just a matter of defining the abstract methods and adding documentation.
Since the AMRVAC frontend is not yet ported to yt 4.0, I won't try to implement this just yet without a solid continuous integration frame I can use locally

**Comment by n-claes** [comment]
I’m also up for this if needed! It may be useful to note that we’ll have an AMRVAC developers meeting the first week of April which will probably be followed by some frontend modifications (but that will not influence this topic much I guess). As we’re probably going to work on the particle routines I’m planning to extend the frontend to include those features as well, so this discussion may come up again at some point.

Especially since yt 4.0 has a complete overhaul of the particle system (performance improvements etc) if I’m not mistaken? So this may be a good time to first port the frontend over to 4.0 and then work on the abstract class etc as @neutrinoceros mentioned
