### ISSUE TITLE
Vorticity Magnitude Field Issue with Newer YT Versions

### ISSUE THREAD

**Issue by whitmanscu** [yt-project/yt#2427]
**Bug summary**

Switching systems and yt versions recently, I've noticed that using yt 3.5.1, vorticity magnitude fields do not render properly (it's possible that the issue lies in the field calculation itself, I'm not sure). This shows up specifically in AMR fields across different levels of refinement, with fields being non-smooth across the interface. Other fields render smoothly. From the yt Slack channel, @ngoldbaum also suggested I ping @atmyers on this issue. Another user on Slack was apparently able to reproduce the issue with yt 4.

**Code for reproduction**
I reproduced this issue using the "TurbBoxLowRes" Orion 2 dataset at [https://yt-project.org/data/](url) using the following simplified code:
```python
import yt
​
ds=yt.load("data.0005.3d.hdf5")                                               
​
sx = yt.SlicePlot(ds, 'z', 'vorticity_magnitude', origin="native")
sx.set_cmap(field="vorticity_magnitude", cmap='Hue Sat Lightness 2')
sx.set_log('vorticity_magnitude', True)
sx.annotate_timestamp(corner='lower_left', draw_inset_box=True)
sx.annotate_grids()
plot = sx.plots['vorticity_magnitude']
cbar = plot.cb
sx._setup_plots()
cbar.set_label('$(\omega\cdot\omega)^{1/2}$ $(\mathrm{1/s})$')
sx.save()
```

**Actual outcome**

Using the same dataset, yt 3.5.1 produces:
![yt_3 5 1](https://user-images.githubusercontent.com/42480906/73216415-2f2ec600-4113-11ea-8274-1c5bb47207f6.png)

**Expected outcome**

yt 3.4.0 produces:
![data 0005 3d hdf5_Slice_z_vorticity_magnitude](https://user-images.githubusercontent.com/42480906/73216585-79b04280-4113-11ea-9146-9e9c7fde1878.png)

**Version Information**

  * Operating System: OSX
  * Python Version: 3.6.7
  * yt version: 3.5.1
  * Other Libraries (if applicable): 

yt was installed from the default Conda branch

**Comment by ngoldbaum** [comment]
Thanks for the report!

**Comment by atmyers** [comment]
I can reproduce this bug. However, on this particular data set, the problem seems to have been fixed already on the current master branch:

3.5.1:

![3 5 1](https://user-images.githubusercontent.com/4329158/73227842-b5ee9d80-4129-11ea-95c0-ef124fb724ce.png)

master:

![master](https://user-images.githubusercontent.com/4329158/73228018-3f9e6b00-412a-11ea-9eb8-2535dc07939e.png)

Any chance updating to master fixes the issue for your dataset as well? I think there is a chance these are actually two different problems, as the Boxlib and Chombo frontends are actually quite different under the hood.

**Comment by pdmullen** [comment]
Potentially related to PR #2398 .

**Comment by whitmanscu** [comment]
Confirmed that after building from source I do not see this issue on yt 3.6.dev0. I'm fine closing this assuming you folks feel similarly.

**Comment by ngoldbaum** [comment]
OK great. Closing now. Hopefully we'll be able to get a release out soon.
