### ISSUE TITLE
region arithmetic funniness

### ISSUE THREAD

**Issue by zingale** [yt-project/yt#2560]
### Bug report

**Bug summary**

If I mix `ds.domain_left_edge` with a list composed of components of `ds.domain_*`, I get a `YTUnitOperationError`

**Code for reproduction**

```python
import numpy as np
import yt

plotfile = "smallplt00595"

ds = yt.load(plotfile)



center = ds.domain_center
lower_left = ds.domain_left_edge
upper_right = ds.domain_right_edge

ll = [lower_left[0], lower_left[1], lower_left[2]]
rr = [center[0], upper_right[1], upper_right[2]]
region1 = ds.box(ll, rr)
print(region1)

ll = lower_left
rr = [center[0], upper_right[1], upper_right[2]]

region2 = ds.box(ll, rr)
```

**Actual outcome**

```
$ python3 test_region.py
yt : [INFO     ] 2020-04-25 14:16:34,930 Parameters: current_time              = 7.24422756567562
yt : [INFO     ] 2020-04-25 14:16:34,930 Parameters: domain_dimensions         = [512 512 512]
yt : [INFO     ] 2020-04-25 14:16:34,930 Parameters: domain_left_edge          = [-5.12e+09 -5.12e+09 -5.12e+09]
yt : [INFO     ] 2020-04-25 14:16:34,930 Parameters: domain_right_edge         = [5.12e+09 5.12e+09 5.12e+09]
YTRegion (smallplt00595): , center=[-2.56e+09  0.00e+00  0.00e+00] cm, left_edge=[-5.12e+09 -5.12e+09 -5.12e+09] cm, right_edge=[0.00e+00 5.12e+09 5.12e+09] cm
Traceback (most recent call last):
  File "test_region.py", line 22, in <module>
    region2 = ds.box(ll, rr)
  File "/raid/zingale/development/yt/yt/data_objects/static_output.py", line 854, in box
    c = (left_edge + right_edge)/2.0
  File "/raid/zingale/development/yt/yt/units/yt_array.py", line 1414, in __array_ufunc__
    inps, units, ufunc, ret_class)
  File "/raid/zingale/development/yt/yt/units/yt_array.py", line 174, in handle_preserve_units
    raise YTUnitOperationError(ufunc, *units)
yt.utilities.exceptions.YTUnitOperationError: The <ufunc 'add'> operator for YTArrays with units (code_length) and (dimensionless) is not well defined.
```

**Expected outcome**

I would expect to for both of these ways to compose a region to work.

**Version Information**

  * Operating System: Fedora 31
  * Python Version: 3.7.6
  * yt version: 3.7.dev0
  * Other Libraries (if applicable): numpy 1.17.4

yt built from source (`python setup.py develop`)

**Comment by neutrinoceros** [comment]
I was able to reproduce this using `yt.testing.fake_amr_ds()` as a dataset, though the error I'm getting is not exactly the same but I gave some insight.
I think what's happening here is that, because of how `Dataset.box()` forces the args (left/right_edge) as numpy arrays, it behaves differently depending on the arguments' form

In this cases, here's what happens during the conversion:
- `[0.0 code_length, 0.0 code_length, 0.0 code_length]` -> `[0.0, 0.0, 0.0]` (units' gone !)
- `YTArray([0., 0., 0.]) code_length` -> stays unchanged

So, unless your errors actually goes deeper, I think I catch patch this very quickly.

**Comment by zingale** [comment]
I tested your PR and it fixes my issue.  Thanks!
