### ISSUE TITLE
Use `fn`, `filename`, `name`, or `my_cool_argname` in the codebase? 

### ISSUE THREAD

**Issue by munkm** [yt-project/yt#2879]
This was brought up in yt-project/yt#2877 and yt-project/yt#2695 . 

The second PR in that list makes the arguments passed to various loader functions consistent. Following other examples in our codebase, `fn` is used as the name of the variable to which we assign the input file (or folder). `fn` does (intentionally, I think, though somebody can correct me) create an ambiguity (between file name and folder name?) since we're not necessarily assuming a file is going to be passed into these loaders. Because we can have a folder passed, `filename` isn't the best name to use because it isn't always correct (same with foldername). The `load_sample` function addressed this by using `name` as this argument's name. 

Does anybody have any suggestions of what to use? I personally think `fn` is misleading because I read it is "function" if I'm scanning code. Is there something better?  

Maybe this is bikeshedding, but since load is what essentially all of our users use to access yt I think choosing a clearer argument name is important.

**Comment by neutrinoceros** [comment]
`fname` is another option that I think we can all agree on rejecting immediately since it's used everywhere to mean "field name".
I would love for this argument to be positional only so that we don't have to embrace a bad name forever. But that's not possible until Python 3.8 becomes our oldest supported Python version (so somewhere along the release of Python 3.10 in October 2021, maybe ?)

**Comment by neutrinoceros** [comment]
`fname` seems to be the dominant convention in numpy for reference (https://numpy.org/doc/stable/search.html?q=fname)
