### ISSUE TITLE
yt.load Unidentified File Type

### ISSUE THREAD

**Issue by jeramkaram** [yt-project/yt#2949]
**Bug summary**
Upon trying to load a Gadget-2 dump file I have named `gas_dump_0.011.5.hdf5` using `yt.load('gas_dump_0.011.5.hdf5')` and I am repeatedly getting a YTUnidentifiedDataType error. Would anyone be able to help out quick? I installed yt from source and not from `pip`. Thank you.
Jeremy

**Comment by neutrinoceros** [comment]
Oh wow I'm so sorry it's taken a full year to see this.
@jeramkaram unfortunately there is not enough information here we can work with to solve your issue, and given how long it's been, I'm going to _assume_ your problem was solved in the mean time, and so I'll close this.

A simple possibility that I see that could explain your problem is that `h5py` wasn't installed in your Python env, but can't confirm without having access to your datafile.

If by any chance you still would like help on this, please ping me and don't hesitate to reopen !
Again, we're sorry about the delay.
