### ISSUE TITLE
ENH: Refactor annotation callbacks

### ISSUE THREAD

**Issue by cphyc** [yt-project/yt#3311]
At the moment the callbacks (and fixed resolution buffer filters) have a very circumvoluted structure which makes them:
- hard to discover in the code base because the class that define them does not match the name used to access them.
- leads to weird issues (see e.g. https://github.com/yt-project/yt/pull/3310 and the issue of the incorrect signature).
- significantly increases the code complexity.

I don't have a solution to _how_ the refactor could be done, but it is probably long overdue!

**Comment by neutrinoceros** [comment]
I support this. I independently arrived to the same conclusions.

**Comment by neutrinoceros** [comment]
Just want to report I found 2 ways the current callback system can be hacked (from the user) to facilitate implementation of the missing bits:

### hack 1.
hard coded geometry restrictions can be lifted as follow (`None` means "any geometry" in this context)
```python
from yt.visualization.plot_modifications import ContourCallback
ContourCallback._supported_geometries = None
```

the only gain here is that one can see the result of any existing callback even for unsupported geometries, without touching the code base.

### hack 2.
One can replace an existing callback class at runtime by simply reregistering an existing name, for instance

```python
from yt.visualization.plot_modifications import PlotCallback

class ContourCallback(PlotCallback):
    _type_name = "contour"
    _supported_geometries = None
  
    def __init__(
          self,
          field_x,
          field_y,
          factor = 16,
          density=1,
          field_color=None,
          display_threshold=None,
          plot_args=None,
    ):
          PlotCallback.__init__(self)
          print("hey !")

    def __call__(self, plot):
        print("doing nothing")
```

It's clearly not designed to be extensible, but it turns out it sorta is. This means that it's possible to package some drop-in replacements as a yt extension, which I'll consider doing to get ahead of the release cycle in the future.

**Comment by neutrinoceros** [comment]
In #3957, I refactored callbacks to improve error handling, which I think resolves the second point.
Now I don't think we can _rename_ the `PlotCallaback` classed as you hinted in the first point, because that would be a breaking change for yt_astro_analysis and anyone subclassing it. Of course there would be way to still rename it while keeping backward compatibility, but at the cost of additional technical debt, which I don't think is warranted.

In #4080, I documented how to extend `annotate_*` methods, because that the only reliable way to add custom annotations without modifying yt's source code. This means that they cannot be treated as implementation details and should be viewed as public API.

For these reasons, I don't think there are actions left to take here, so I'll close.
