### ISSUE TITLE
linking rockstar with yt 

### ISSUE THREAD

**Issue by Jessica-Lopez** [yt-project/yt#3357]
Hello there!

I'm trying to install yt with rockstar. First, I tried using the repository 

https://github.com/yt-project/yt

and the installation occurs without any trouble. But when I import yt, this message is displayed

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

So, my second try was using the command

bash install_script.sh

and in order to install support for the rockstar  halo finder, I wrote in the script the line  INST_ROCKSTAR=1.  However when I try to import rockstar the following error is displayed

ImportError: cannot import name 'rockstar_interface' from 'yt.analysis_modules.halo_finding.rockstar' (/home/jessica/Programas/yt-conda/lib/python3.8/site-packages/yt/analysis_modules/halo_finding/rockstar/__init__.py)

Is it  possible to  install the support for the rockstar halo finder yet?

In that case, how can I do that?

Best,
Jessica

**Comment by neutrinoceros** [comment]
Hi @Jessica-Lopez !

1) the numpy error is due to a difference between the version of numpy that was used to compile yt and the one you have installed in your environment. This is normally solved by upgrading numpy (`python -m pip install -U numpy`)
2) Installing rockstar + yt is a little bit tricky. Rockstar support was moved to yt_astro_analysis (https://github.com/yt-project/yt_astro_analysis/), please see instructions therein on how to add rockstar compatibility.

The specific import error you're seeing may also mean that you'll need to edit some of your import statements to point to yt_astro_analysis. 

I'm closing this for now because I don't think there is anything to be done in yt itself to help you now, but feel free to open another issue on yt_astro_analysis if my small hints were not enough to solve your problem
(also @brittonsmith, I'm pinging you to make sure you've seen this, maybe you'll want to reopen too if I've missed something)
