### ISSUE TITLE
Release documents need updating 

### ISSUE THREAD

**Issue by munkm** [yt-project/yt#3448]
Our release docs are out of date since we've updated our project infrastructure related to releases. We need to update the sections in the release docs to make sure these are clear.

**Comment by stonnes** [comment]
@neutrinoceros and @matthewturk I think in the future we should not unassign people who have assigned themselves without a written verification that it is ok (even better is if they unassign themselves!)

**Comment by stonnes** [comment]
Yeah, I see that.  I think it is great that you stepped in and assigned yourself to resolve the issue since Madicken put herself in the fallow fields.  I just don't think it was necessary to unassign her.  I think this issue could still be moved forward and closed without actively removing someone--if I am wrong and issues cannot be closed without removing people, definitely let me know!

**Comment by neutrinoceros** [comment]
You're right, it's not blocking. I probably shouldn't have assigned myself instead, let alone Matt.
I don't think we have a clear policy for assignments actually, I would err on the side of not using them at all, following the advice given here https://www.redhat.com/en/blog/dont-lick-cookie

**Comment by stonnes** [comment]
Okay, until that conversation happens about how yt should be using the assign feature, I am putting @munkm back on and she can stay or remove herself.
