### ISSUE TITLE
Lorentz-Heaviside Magnetic Units vs CGS

### ISSUE THREAD

**Issue by forrestglines** [yt-project/yt#3471]
I ran into some confusing behavior with magnetic fields while creating a yt frontend for Parthenon/AthenaPK using the Athena++ frontend as a base. I realize that the current Athena++ frontend treats the magnetic fields in CGS but within the code magnetic fields are treated with Lorentz-Heaviside units (i.e. there are no factors of 4 pi in Maxwell's equations, magnetic pressure is "B^2/2"). This leads to some awkward differences between expressions in the code and expressions in an analysis with yt.

For example for the magnetic energy density/pressure
```python
#Won't match yt
ad_cons["athena_pp","Etot"]

magnetic_energy_density = 0.5*( ad_prim["athena_pp","Bcc1"]**2
                               +ad_prim["athena_pp","Bcc2"]**2
                               +ad_prim["athena_pp","Bcc3"]**2)

#Won't match
ad_cons["gas","magnetic_energy_density"]
```
and when calculating the total energy density:
```python
#As implemented in the code
Etot = 0.5*ad_prim["athena_pp","rho"]*( ad_prim["athena_pp","vel1"]**2 
                                       + ad_prim["athena_pp","vel2"]**2
                                       + ad_prim["athena_pp","vel3"]**2) \
      + ad_prim["athena_pp","press"]/(gamma-1) \
      + 0.5*( ad_prim["athena_pp","Bcc1"]**2
             +ad_prim["athena_pp","Bcc2"]**2
             +ad_prim["athena_pp","Bcc3"]**2)

#Won't match yt
ad_cons["athena_pp","Etot"]
```
Both these expressions need factors of 1/4pi in the analysis that don't appear in the code.

The community has seemed to have gotten by fine with the Athena++ frontend by just writing their analysis in Gaussian units while the code lives in Lorentz-Heaviside units. However, this has become awkward when we're trying to use yt to verify AthenaPK code since it's not always obvious where extra factors of 1/4pi need to be included in our analysis.

Is it possible to change how `yt` computes magnetic pressure? Or would it be feasible to add a "lorentz_heaviside" unit system that fits within the CGS unit system but uses the "B^2/2" convection for magnetic pressure?

**Comment by jzuhone** [comment]
I'm a bit surprised about one thing. yt has fields (e.g.) `("gas","magnetic_field_x")` which are derived from `("athena_pp","Bcc1")`, except that the former assume the "Gaussian" convention and the latter (coming from Athena++) assume the Lorentz-Heaviside convention. Because of this, when one tries to compute the magnetic pressure, the values from the expression you gave above using the Athena++ fields and the values from the `"magnetic_energy_density"` field should be equal, because the magnetic fields are supposed to pick up the factor of 4*pi. 

However, now I notice that for some reason the Athena++ test dataset we have with magnetic fields seems to think that the `code_magnetic` unit is SI, which is definitely a bug, so I can't test this. This may be why the expressions above are not equal for you, because they really should be, and at least for expressions like the magnetic energy density or pressure which are independent of the convention this should not be a problem. 

With regard to having a Lorentz-Heavisde convention in yt, I thought about doing this once, but when I tried to sketch out what one would have to do with the code I determined it was pretty tricky. It may be worth going back to. 

In ay case, there's a bug that needs fixing now.

**Comment by jzuhone** [comment]
I'm a bit surprised about one thing. yt has fields (e.g.) `("gas","magnetic_field_x")` which are derived from `("athena_pp","Bcc1")`, except that the former assume the "Gaussian" convention and the latter (coming from Athena++) assume the Lorentz-Heaviside convention. Because of this, when one tries to compute the magnetic pressure, the values from the expression you gave above using the Athena++ fields and the values from the `"magnetic_energy_density"` field should be equal, because the magnetic fields are supposed to pick up the factor of 4*pi. 

However, now I notice that for some reason the Athena++ test dataset we have with magnetic fields seems to think that the `code_magnetic` unit is SI, which is definitely a bug, so I can't test this. This may be why the expressions above are not equal for you, because they really should be, and at least for expressions like the magnetic energy density or pressure which are independent of the convention this should not be a problem. 

With regard to   I thought about doing this once, but it's tricky.

**Comment by jzuhone** [comment]
For some reason my comment got mangled above, I just fixed it.
