### ISSUE TITLE
DEPR: deprecate annotate_halos (HaloCatalogCallback)

### ISSUE THREAD

**Issue by brittonsmith** [yt-project/yt#3566]
As soon as [PR #98](https://github.com/yt-project/yt_astro_analysis/pull/98) in yt_astro_analysis is accepted, the HaloCatalogCallback should be deprecated or removed. This will get rid of the need to import yt_astro_analysis inside yt itself.

**Comment by neutrinoceros** [comment]
as we discussed yesterday, it probably doesn't need to be formally deprecated because (I think ?) nobody is going to miss it: it will stay available for yt_astro_analysis users, and I expect it that the migration is going to be 100% transparent to them ?
We can add an item to yt 4.1 release notes specifically for yt_astro users, saying that they should upgrade it too, but other than that I think we should be good.

**Comment by brittonsmith** [comment]
Yeah, I think I am fine with skipping deprecation. I wonder if we could put a function in place that raises an exception and informs the user what to do.
