### ISSUE TITLE
ENH: encapsulate axis flipping method

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#3631]
### Bug report

**Bug summary**

`PlotWindow` is missing a method to flip horizontal and vertical axes. There is somewhat hacky workaround on the user side but it isn't perfect, as showcased bellow.

**Code for reproduction**

```python
import yt

ds = yt.load_sample("IsolatedGalaxy")
slc = yt.SlicePlot(ds, "x", "density")
slc.zoom(10)
slc.save("/tmp/zy.png")

ds.coordinates.x_axis["x"] = 2
ds.coordinates.x_axis[0] = 2
ds.coordinates.y_axis["x"] = 1
ds.coordinates.y_axis[0] = 1
slc = yt.SlicePlot(ds, "x", "density")
slc.zoom(10)
slc.save("/tmp/yz.png")
```

**Actual outcome**
native
![zy](https://user-images.githubusercontent.com/14075922/139573696-1ba15bcc-6b89-44c4-8914-fd3e564f83a4.png)
flipped
![yz](https://user-images.githubusercontent.com/14075922/139573698-68819e7a-eb05-41e8-9c73-1ff67b55e7ef.png)

**Expected outcome**

axis labels should be flipped too. Currently this is achievable but it necessitates more work on the user side.
The reason that they are not flipped is because we're changing the coordinate system on the fly, rather than the figure itself, so the result makes sense, but it's not what "flipping axis" means in the plotting context.

Another undesirable effect can be seen when the region plotted isn't squared: the figure size can drastically vary after the axes were flipped, as can be seen in #3630 
This is arguably a different but related issue, so I'll open a separate report.

_Originally posted by @neutrinoceros in https://github.com/yt-project/yt/issues/3630#issuecomment-955628272_

**Comment by matthewturk** [comment]
Should this also include the direction of the normal vector, to control the positive/negative direction of the display axes?

**Comment by neutrinoceros** [comment]
Yes that's also something I think we should support, and I agree that the two actions are related enough that it makes sense to work on both at the same time.

**Comment by chrishavlin** [comment]
A few notes since I spent some time experimenting this yesterday:

The hacky workaround only works for cartesian datasets since `PlotWindow`... Not surprising, but it illustrates how the image display axes are tied in directly with the frb generation and pixelation routines. 

And in terms of the hacky workaround example: the axis labels don't swap there because the base `CoordinateHandler` caches an `_image_axis_name` attribute the first time you generate a plot. If you re-load `ds` after the first plot the axis labels will flip. 

I experimented with transposing the frb and swapping axis labels in `PlotWindow` and it worked in simplified cases, but it got tricky very quickly when thinking through how to generalize, especially when there are multiple plot elements.

**Comment by neutrinoceros** [comment]
> I experimented with transposing the frb and swapping axis labels in PlotWindow and it worked in simplified cases, but it got tricky very quickly when thinking through how to generalize, especially when there are multiple plot elements.

this sounds like the way to go if we want to make it as general as possible. I wouldn't want to have another region of the code where curvilinear coordinate systems need special casing. I fail to anticipate the difficulties that arise with more than one plot element though, and if you think it's still going somewhere I'd be happy to have a look at a draft PR with what you have so far !

**Comment by chrishavlin** [comment]
by more than one plot element I meant plot callbacks (check out the draft PR for a discussion of that)
