### ISSUE TITLE
pyproject.toml contains an invalid dependency 'oldest-supported-numpy'

### ISSUE THREAD

**Issue by yurivict** [yt-project/yt#4059]
In [this](https://github.com/yt-project/yt/blob/main/pyproject.toml#L10) line.

Build module fails to build it:
```
ERROR Missing dependencies:
	oldest-supported-numpy
*** Error code 1
```

Version: 4.0.4

**Comment by neutrinoceros** [comment]
What do you mean invalid ? [oldest-supported-numpy](https://pypi.org/project/oldest-supported-numpy/) is a meta-package that allows us to use the first numpy version that is known compatible with the target platform + Python version, at build time.

Essentially all of their code reside here https://github.com/scipy/oldest-supported-numpy/blob/main/setup.cfg
We've been using it since yt 4.0.0, so I'm surprised this pops up only now. I assume you're in the process of packaging yt 4.0.4 for FreeBSD ?

**Comment by yurivict** [comment]
The "build" package complains about "oldest-supported-numpy".
But we on FreeBSD don't have packages for Python's meta packages, so we will have to patch that out.

Thank you for this information.
