### ISSUE TITLE
Nose test dependency

### ISSUE THREAD

**Issue by olebole** [yt-project/yt#4102]
### Bug report

For the Debian package, I received a bug report [Debian#1018675](https://bugs.debian.org/1018675), that yt depends on the nose test framework. Nose is [dead](https://github.com/nose-devs/nose/commit/0f40fa995384afad) and [unmaintained](https://pypi.org/project/nose/#history) since several years, and in Debian we would like to remove nose at some point.

Would it be possible to migrate to [pytest](https://docs.pytest.org) (what I would prefer), or to [nose2](https://docs.nose2.io/) or so?

**Version Information**
  * Operating System: Debian bookworm (upcoming)
  * Python Version: 3.10
  * yt version: 4.0.5

**Comment by neutrinoceros** [comment]
Hi @olebole, this has been on our radar for quite some time and we are well aware that nose is unmaintained.

Migration to pytest is absolutely our plan in the long run, but it’s bound to be a large effort for us since many of our tests are yield-based, and cannot be run with pytest as they exist now.

However I wasn’t personally aware of the existence of nose2. I will look it up to see if it can be switched to in a transparent manner.

**Comment by neutrinoceros** [comment]
It looks like nose2 isn't a drop-in replacement for nose as I hoped, so if even switching to that isn't trivial, I don't think it's worth doing, and our energy is better spent on migrating to pytest directly.
It's a substantial effort and we're currently relying only on volunteer work to perform this migration, so I don't know when we can expect completion, but probably not in the immediate future, and it seems definitely out of reach for existing and upcoming yt releases, I'm sorry about that

**Comment by neutrinoceros** [comment]
I created a repo level project to keep track of the existing effort and things that are left to be done here https://github.com/yt-project/yt/projects/4
