### ISSUE TITLE
Consider adding linting for cython code

### ISSUE THREAD

**Issue by ngoldbaum** [yt-project/yt#4193]
I learned today about a linter that's being worked on  for cython code, based on existing linters for Python code:

https://github.com/MarcoGorelli/cython-lint

It might be helpful to turn this on for yt's cython code.

**Comment by matthewturk** [comment]
That's pretty cool.  Thanks, @ngoldbaum .  I'd be up for taking on linting stuff.  If I am remembering right I think you and also @Xarthisius have taken passes at linting some/all of the Cython code for the Cython-level errors, and maybe this would be a good way to finish that up and also keep us in line for the future.

**Comment by ngoldbaum** [comment]
Marco says that the project is still new so please report any bugs you run into.

**Comment by neutrinoceros** [comment]
I gave it a try and AFAICT the warnings fall in 3 categories:
1) unused imports
2) unused variables
3) style nits (can be deactivated with `--no-pycodestyle`)

To me, 3) is just noise, but since it is optional, I don't see it as a problem.
1) 2) however would be easy to solve (however boring). I addressed 1) in #4195
