### ISSUE TITLE
Continued problems with stored EWAH files

### ISSUE THREAD

**Issue by jzuhone** [yt-project/yt#4371]
### Bug report

After https://github.com/yt-project/yt/pull/4307/, there are still some problems with loading the particle bitmap index from the EWAH sidecar file. 

**Code for reproduction**

```python
import yt
ds = yt.load("cutout_58.hdf5")
sp = ds.sphere([8142.44, 14341.0, 25125.9], (20.0, "kpc"))
print(sp.sum(("PartType0", "particle_mass")))
```

**Actual outcome**

Before dumping the EWAH file:

```pycon
yt : [INFO     ] 2023-03-11 12:32:41,144 Calculating time from 1.000e+00 to be 4.356e+17 seconds
yt : [INFO     ] 2023-03-11 12:32:41,182 Parameters: current_time              = 4.355810528213311e+17 s
yt : [INFO     ] 2023-03-11 12:32:41,182 Parameters: domain_dimensions         = [1 1 1]
yt : [INFO     ] 2023-03-11 12:32:41,183 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2023-03-11 12:32:41,183 Parameters: domain_right_edge         = [35000. 35000. 35000.]
yt : [INFO     ] 2023-03-11 12:32:41,183 Parameters: cosmological_simulation   = 1
yt : [INFO     ] 2023-03-11 12:32:41,183 Parameters: current_redshift          = 2.220446049250313e-16
yt : [INFO     ] 2023-03-11 12:32:41,183 Parameters: omega_lambda              = 0.6911
yt : [INFO     ] 2023-03-11 12:32:41,183 Parameters: omega_matter              = 0.3089
yt : [INFO     ] 2023-03-11 12:32:41,183 Parameters: omega_radiation           = 0.0
yt : [INFO     ] 2023-03-11 12:32:41,183 Parameters: hubble_constant           = 0.6774
yt : [INFO     ] 2023-03-11 12:32:41,211 Allocating for 1.504e+07 particles
Initializing coarse index : 100%|██████████████████████████████████████████████████████████| 37/37 [00:00<00:00, 96.12it/s]
yt : [INFO     ] 2023-03-11 12:32:41,616 Updating index_order2 from 2 to 4
Initializing refined index: 100%|██████████████████████████████████████████████████████████| 37/37 [00:01<00:00, 27.47it/s]
0.598708856382018 code_mass
```

After it is read in on the second time running the same script:

```pycon
yt : [INFO     ] 2023-03-11 12:34:51,407 Calculating time from 1.000e+00 to be 4.356e+17 seconds
yt : [INFO     ] 2023-03-11 12:34:51,445 Parameters: current_time              = 4.355810528213311e+17 s
yt : [INFO     ] 2023-03-11 12:34:51,445 Parameters: domain_dimensions         = [1 1 1]
yt : [INFO     ] 2023-03-11 12:34:51,445 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2023-03-11 12:34:51,445 Parameters: domain_right_edge         = [35000. 35000. 35000.]
yt : [INFO     ] 2023-03-11 12:34:51,446 Parameters: cosmological_simulation   = 1
yt : [INFO     ] 2023-03-11 12:34:51,446 Parameters: current_redshift          = 2.220446049250313e-16
yt : [INFO     ] 2023-03-11 12:34:51,446 Parameters: omega_lambda              = 0.6911
yt : [INFO     ] 2023-03-11 12:34:51,446 Parameters: omega_matter              = 0.3089
yt : [INFO     ] 2023-03-11 12:34:51,446 Parameters: omega_radiation           = 0.0
yt : [INFO     ] 2023-03-11 12:34:51,446 Parameters: hubble_constant           = 0.6774
yt : [INFO     ] 2023-03-11 12:34:51,470 Allocating for 1.504e+07 particles
Loading particle index: 100%|████████████████████████████████████████████████████████████| 37/37 [00:00<00:00, 6296.73it/s]
0.0 dimensionless
```

**Expected outcome**

Result should be the same regardless of whether we use the stored EWAH file or not. 

**Version Information**

  * Operating System: macOS Ventura 13.1 (ARM)
  * Python Version: 3.11.0
  * yt version: 0824f9883180cbb9d3dee0e176f43f821c869207
  * Other Libraries (if applicable):

From source (`pip install -e .` in yt directory)

**Comment by jzuhone** [comment]
@Xarthisius I am happy to poke around in the code from your original PR if you could give me a hit as to what part of it I should look in for the wrong thing it's doing

**Comment by neutrinoceros** [comment]
Just noticed that #3327 was never closed. Should it be kept open still ?

**Comment by jzuhone** [comment]
I figured it out--If the `index_order2` gets updated, then it gets set before we create the EWAH file, and it's stored there. then we simply have no choice but to read the "correct" one back from the file, even though in #4307 @Xarthisius had them as "informational" and not used as part of the calculation. I'll see if I can think of a different way, however.

**Comment by jzuhone** [comment]
But please note that this makes it even harder to hide our dependence on `h5py` for this

**Comment by matthewturk** [comment]
OK, I wrote some thoughts up.

# EWAH Indexing Strategy

Free parameters:
- Is a bounding box applied to the dataset? *Do we want to exclude particles?*
- Does the dataset have a pre-specified domain for the particles to reside in? *Do we know the bounds?*
- Do we specify the index order? *Can we guess the distribution of particles for indexing purposes?*

Order of operations:

1. If a bounding box or domain is not specified, pass over the data via `ds.index.io._yield_coordinates` and compute min/max.  Grow this by 5% in all directions.  (I think this logic may be flawed, however, as it's a strict multiplication, when what I believe we should do is compute the domain width, then grow by 5% of that in each direction.
2. If there is only a single data chunk (not a single data file, but a single chunk of the variable chunksize) set the index order to 1, 1, so that no index is not constructed.
3. `dont_cache` variable is set if and only if `order1 == order2 == 1` which can either be a result of manually specifying the order or by the condition above.
4. A new instance of `ParticleBitmap` is created, which has `index_order1` and `index_order2` specified.  Note that we *can* change these later, but it requires calling `reset_bitmasks` which is done in order to re-allocate the internal data structures and remove any cached values.
5. `dont_load` is set, which is set in the case that `dont_cache` *is* set, *and* `index_filename` isn't set.  I believe this is in case we end up in a situation where we want to load something, but we otherwise have `dont_cache` set.  To be honest, I'm not sure I understand.
6. In the case that we are able, we call `load_bitmasks` and `check_bitmasks`.  These only have one way of signaling failure that can be handled -- raising either `OSError` or `struct.error`, and I think that for the former we assume it's because the file doesn't exist and the latter because the structure was either of the wrong version or malformed.
7. In the *other* case, where either the index doesn't exist or can't be used, we first call `reset_bitmasks` and conduct two passes over the data.
8. Call `_initialize_coarse_index` first.
	1. This passes over every chunk (in parallel) and looks at every particle type and position type.
	2. For those particle types that have smoothing length fields, we also track the maximum smoothing length that is found in the data files.
	3. These positions are then fed in to `_coarse_index_data_file` which constructs the coarse EWAH for each chunk.
	4. These are then finalized after a parallel reduction.
	5. Collisions are identified and marked (internally.)  This is a simple matter of finding any coarse cell index that has more than one file marked as including it.
	6. If a maximum smoothing length has been found, and if there is more than one data file, call `update_mi2`.  This is a simple operation, *but*, it also somehow needs to pass information back up, or have information passed down.  It always gets called if `max_hsml` is found, regardless of whether or not we specified the index manually.
	7. If appropriate, set it to no more than 2 higher than it currently is, but try to make it so it encompasses the appropriate smoothing length size.
9. Call `_initialize_refined_index` next.
	1. Here, we do some heuristics.  We have (leftover) the counts of particles in each of the coarse cells, so that we can try to figure out if we want to refine them or not.  This information comes from `_index_mask_threshold` and `_index_count_threshold`, which default to 2 (i.e., one overlapping file is enough) and 256 (i.e., with more than 256 particles in it).
	2. Iterate (in parallel again) over all `data_files` (which are chunks) and particle types:
		1. Read that particle type's position and smoothing lengths (if available).  Pass this information along with the thresholding information in to the refined index.
		2. Mark all zones *and ghost zones* as being present if they are marked.  *This* is the tricky bit!  Because the smoothing length can wildly vary, if we have a big smoothing length and a very fine index, it can actually take a very long time to mark all the zones as being present, because there are so many.
	3. Identify all colliding refined zones.  We don't iterate again, but it's important to have this information.
10. Now, given that `index_order2` may have been updated, we re-generate the index filename.
11. If `dont_cache` isn't set, and we can access the index filename, we save the bitmasks for our *current* `index_order1` and `index_order2`.

So here's the problem as I see it.  We have several things going on, the first of which is that at present, we have several pieces of information that we do not communicate:

 - Are we using default values for the `index_order1` and `index_order2` arguments?  If *not*, then those should override whatever else we're doing!  But at present we can't figure this out.
 - If we are guessing, are we just going to always re-guess the thing that's in the index file?  If so, we will pass over the full dataset *every time* only to find ourselves back at that.

I see a couple mitigating strategies:

 - In the index file, also store the extrema of the particle values, including the smoothing length.  Use this if it is available to reduce the number of passes over the dataset by one in the case that we are not specifying a bounding box.  We should *also* store the "autoguessed" `index_order` values here, to be used in case an index is not specified.
- If the index order is specified, you can use the info above, but there should be a flag that indicates no modification is allowed to the `index_order` values.
- If the index order is not specified, look for one that is available, and reset the requested index order to that, and do not modify `index_order2` based on any further information.

I believe we can approach this with a straightforward refactoring.  We can move some of the indexing parameters into a special dataclass, which gets passed around as a whole.  (No methods, just data.)  This will let us add more boolean flags, like, "was this overridden" and whatnot, without polluting the `ParticleGeometryHandler` namespace.

This is the parameter space to consider:

- Bounding box is specified / not specified
- Domain is specified / not specified
- Index order is specified / not specified
- Index for specified index exists / does not exist
- Index for unspecified index exists / does not exist

The final one seems the trickiest to me, as it takes place in the space of possibility where an index should be guessed, but we do not yet know what the appropriate guess should be.  Adding the "guessed index" values to metadata in the index file would address this.

So here's what I think we should do:

1. Create a simple dataclass that contains `index_order1`, `index_order2`, `index_filename`, `override_defaults`, and whatever else we need.  If `override_defaults` is specified, then we know we should freeze `index_order1` and `index_order2`.  If it is not, then we can modify them.
2. Pass this around rather than store exclusively in parameters on the `ParticleIndex` object, and then at the end of the indexing process update the `ParticleIndex` attributes (and discard this object.)
3. Add metadata to the `index_filename` that stores the position extrema and the maximum smoothing length.  (One interesting issue I just realized is that the maximum smoothing length may vary considerably in high-dynamic range datasets if we specify a bounding box or we don't.  Perhaps we could store it in a bounding-box specific attribute.)

Does this sound acceptable?

**Comment by jzuhone** [comment]
Yes, I agree with this approach.
