### ISSUE TITLE
multiplot_export_to_mpl gets colorbar orientation wrong

### ISSUE THREAD

**Issue by zingale** [yt-project/yt#4382]
### Bug report

**Bug summary**

If I rerun the `multiplot_export_to_mpl.py` cookbook example, but put the colorbars at the bottom, then
the orientation of the colorbar is set incorrectly.

**Code for reproduction**

This is a 1-line change from the cookbook:

```python
import yt

ds = yt.load_sample("IsolatedGalaxy")

fields = [
    ("gas", "density"),
    ("gas", "velocity_x"),
    ("gas", "velocity_y"),
    ("gas", "velocity_magnitude"),
]

p = yt.SlicePlot(ds, "z", fields)
p.set_log(("gas", "velocity_x"), False)
p.set_log(("gas", "velocity_y"), False)

# this returns a matplotlib figure with an ImageGrid and the slices
# added to the grid of axes (in this case, 2x2)
fig = p.export_to_mpl_figure((2, 2), cbar_location="bottom", cbar_pad="10%")

fig.tight_layout()

fig.savefig("multiplot_export_to_mpl.png")
```

```python
# Paste your code here
#
#
```

**Actual outcome**

Here's the output

![multiplot_export_to_mpl](https://user-images.githubusercontent.com/7817509/227807273-b93d86ea-f4cf-402b-a7af-325ab81d66e6.png)

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

The orientation of the colorbar data appears to be vertical, even though the colorbar itself is presented
horizontally.  I can't seem to find where in yt this is done.

**Version Information**

  * Operating System:
  * Python Version:
  * yt version:
  * Other Libraries (if applicable):

**Comment by zingale** [comment]
yep, it's still an issue with just a single axis.  I don't know if it ever worked.  I can't find any examples in the yt docs with the colorbar on the bottom or top

**Comment by zingale** [comment]
yep, it's still an issue with just a single axis.  I don't know if it ever worked.  I can't find any examples in the yt docs with the colorbar on the bottom or top

**Comment by neutrinoceros** [comment]
This may have been overlooked in #2790 were we simply re-exposed every arguments from `mpl_toolkits.axes_grid.ImageGrid` but didn't thoroughly tested them.
I don't have a clear idea where to begin inspection, but a possible starting point would be to look for where `ImagePlotMPL._get_best_layout` is being defined and used.

**Comment by zingale** [comment]
yep, I wrote that one ;)

but I still cannot find any example, with or without imagegrid, of a sliceplot working with a colorbar on the bottom.  I'll try to find a test for that.

**Comment by xshaokun** [comment]
hi @zingale and @neutrinoceros, I just encountered this issue. When I tried to see how the colorbar of `ImagePlotMPL` was created, I found that no parameters related to this were passed, if I’m not mistaken. Therefore, the colorbar created  [here](https://github.com/yt-project/yt/blob/c9b12af8d3315de72c575a717ac3b14daae8f6e4/yt/visualization/base_plot_types.py#L344) should always follow the default setting, which is vertical.

```python
# the current code for creating colorbar in ImagePlotMPL()._set_axes()
self.cb = self.figure.colorbar(self.image, self.cax)
``` 

Here, it's also necessary to specify the keyword `location` or `orientation`. The `cax.orientation` in `AxesGrid` can tell us the direction of the colorbar. However, `orientation` actually stores position information, such as "top," "left," etc. Therefore, I believe the appropriate correction should be like follows.

```python
self.cb = self.figure.colorbar(self.image, self.cax, location=self.cax.orientation) 
``` 

Since I encountered some issues when installing the python package from source locally, I am unable to test whether this actually solves the problem. Hopefully, if you have time, you can give it a try. I expect this should be able to solve the issue, but it will obviously cause errors in other cases, so I hope you have a better way to solve it : )

FYI,  this feature (matplotlib/matplotlib#25015) also seems to be able to solve our problem, but in the future.

**Comment by zingale** [comment]
as written this does not work:
```
  File "/home/zingale/development/yt/yt/visualization/plot_window.py", line 2551, in __init__
    self._init_image(data, extent, aspect, alpha=alpha)
  File "/home/zingale/development/yt/yt/visualization/base_plot_types.py", line 332, in _init_image
    self._set_axes()
  File "/home/zingale/development/yt/yt/visualization/base_plot_types.py", line 344, in _set_axes
    self.cb = self.figure.colorbar(self.image, self.cax, location=self.cax.orientation)
                                                                  ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Axes' object has no attribute 'orientation'
```

**Comment by xshaokun** [comment]
> as written this does not work:
> 
> ```
>   File "/home/zingale/development/yt/yt/visualization/plot_window.py", line 2551, in __init__
>     self._init_image(data, extent, aspect, alpha=alpha)
>   File "/home/zingale/development/yt/yt/visualization/base_plot_types.py", line 332, in _init_image
>     self._set_axes()
>   File "/home/zingale/development/yt/yt/visualization/base_plot_types.py", line 344, in _set_axes
>     self.cb = self.figure.colorbar(self.image, self.cax, location=self.cax.orientation)
>                                                                   ^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'Axes' object has no attribute 'orientation'
> ```

This is exactly the kind of situation I mentioned that could lead to errors, as the error arises from the fact that the colorbars generated by SlicePlot and ImageGrid use different axes classes, so they need to be distinguished.
```python
        from mpl_toolkits.axes_grid1.axes_grid import CbarAxesBase
        if isinstance(self.cax, CbarAxesBase):
            self.cb = self.figure.colorbar(self.image, self.cax, location=self.cax.orientation)
        else:
            self.cb = self.figure.colorbar(self.image, self.cax)
``` 

I have already tested it locally and it worked, but there are still some formatting issues that need to be improved.
### cbar_location="bottom"
![image](https://github.com/user-attachments/assets/9a4ae2dd-effa-4ae2-9605-0dba35a645e0)

### cbar_location="top"
![image](https://github.com/user-attachments/assets/d511a1ea-1636-4c56-be45-99c9430daf25)

**Comment by neutrinoceros** [comment]
@xshaokun thanks, this looks promising !

> the colorbars generated by SlicePlot and ImageGrid use different axes classes

Do you have a feeling of *why* that is ? it might be a good opportunity to unify those instead of adding `if/else` branches everywhere (but I haven't looked it up myself, it might also be more difficult that I'm naively assuming).

Re: formatting issues (plural): the only one I'm seeing in your example is that the colobar's caption might overlap with the x-axis' label. What else isn't working ?

We could disregard overlaps at first (assuming we have the same problem if one passes `cbar_location="left"`), but I'm hopeful we could also make the code smart enough to move the x or y axis labels and tick labels to the opposite side of the colorbar as needed.

I'd also be happy to assist you in solving your building issues (it would help a lot if you want to open a PR later). Drop me a line on slack or by email if you'd like !

**Comment by xshaokun** [comment]
> Do you have a feeling of _why_ that is ? it might be a good opportunity to unify those instead of adding `if/else` branches everywhere (but I haven't looked it up myself, it might also be more difficult that I'm naively assuming).

Hi @neutrinoceros, I suspect that ImageGrid uses its own cbarAxes to automatically adjust the direction of the colorbar and to hide certain colorbars when drawing multiple plots, as required. While for general plotting, the direction and position of the colorbar rely more on manual specification.

> Re: formatting issues (plural): the only one I'm seeing in your example is that the colobar's caption might overlap with the x-axis' label. What else isn't working ?

This is also the only issue I’ve noticed so far. Like you said, with some adjustments when plotting, it can indeed be avoided.

> I'd also be happy to assist you in solving your building issues (it would help a lot if you want to open a PR later). Drop me a line on slack or by email if you'd like !

Thank you very much! I’ve solved the issue by creating a new python environment, but it still exists in the old one, possibly because my old environment got a bit messy. If I have to face it again in the future, I’ll reach out to you for help!

**Comment by neutrinoceros** [comment]
Oh, it just hit me that `ImageGrid` isn't a class from yt but from mpl. I guess we can't fix that then. Do you want to open a PR with your proposed patch ?

**Comment by xshaokun** [comment]
> Oh, it just hit me that `ImageGrid` isn't a class from yt but from mpl. I guess we can't fix that then. Do you want to open a PR with your proposed patch ?

I'm willing to:) But if it requires a test for it, I'll need your help.

**Comment by neutrinoceros** [comment]
sure, go for it, we can discuss the details there !
