### ISSUE TITLE
BUG: `load_sample` is not MPI-safe

### ISSUE THREAD

**Issue by matthewturk** [yt-project/yt#4635]
We should decorate the appropriate function in `load_sample` so that it doesn't get run on all processors after `enable_parallelism` has been called.

**Comment by neutrinoceros** [comment]
In fact almost the whole function would require special treatment to be parallel-safe. The current higher order function (`yt.func.only_on_root`) doesn't feel as appropriate as I'd like (though the goal *is* achievable with it), because it doesn't make processes *await* the working process (root).

I think this strategy would be better expressed as a new context manager.

**Comment by chrishavlin** [comment]
> I think this strategy would be better expressed as a new context manager. 

does `yt/utilities/parallel_tools/parallel_analysis_interface.parallel_root_only` not work? that seems to dispatch a function call and block the other processes. and looks to be fine to use when `enable_parallelism` has not been called.

**Comment by chrishavlin** [comment]
answered my own question -- and the answer is sort of. That `parallel_root_only` won't broadcast a result so would need to modify it to optionally broadcast a result (instead of the `all_clear` integer) or just write a new function... but I do have something that seems to work. I'll push it up in a moment.
