### ISSUE TITLE
TST: GAMER answer tests are failing

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#4814]
I noticed that since https://tests.yt-project.org/job/yt_py310_git/7894/, 62 answer tests (all GAMER) have been failing on the backport branch (yt-4.3.x).
So far, my only suspect is d1d9a68f8a89679df7505766ed537d62c69fd20c (from #4782), but it wasn't merged yet, so I'm not sure I understand how it can affect other runs (especially on a separate branch).
Is there anything to be done here ? Is this just an unfortunate shortcoming of the answer test system that we should ignore for backports ?

ping @Xarthisius and @jzuhone

**Comment by jzuhone** [comment]
We updated the dataset used on the build box (JetICMWall) for those tests so that's the reason. The fact that it coincides with this commit is (somewhat of) a coincidence.

@hyschive, the head GAMER developer, has already approved PR https://github.com/yt-project/yt/pull/4782, so it would be helpful to have a second approval for just code style, etc on it.

**Comment by neutrinoceros** [comment]
Looks like it's actually affecting the dev branch too.

**Comment by jzuhone** [comment]
This of course completely expected

**Comment by neutrinoceros** [comment]
This wasn't clear to me from your previous message. Am I understanding correctly now that #4782 went in, the problem is resolved on main *and* unsolvable on the backport branch ?

**Comment by jzuhone** [comment]
That's correct.

**Comment by neutrinoceros** [comment]
Thanks ! Then I guess there's no actionable here, so let's close. I'll keep this in mind when checking CI on the backport branch, and it should be completely resolved once we branch out yt-4.4.x
