### ISSUE TITLE
Ambiguous field names should error instead of guessing the field type

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#832]
Originally reported by: **jmoloney (Bitbucket: [jmoloney](https://bitbucket.org/jmoloney), GitHub: [jmoloney](https://github.com/jmoloney))**

----------------------------------------

For Enzo datasets, using the field name 'dynamical_time' instead of the full field ('all', 'dynamical_time'), ('io', 'dynamical_time'), or ('gas', dynamical_time') produces inconsistent results. As far as I can tell, this is because it is the only field that is defined with the same name for both particles and gas. Depending on which fields have been called previously, the field returned by 'dynamical_time' may be either one or the other. I haven't been able to figure out a clear pattern for when each is returned.

This example illustrates the issue:

```
#!python

import yt

pf = yt.load('IsolatedGalaxy/galaxy0030/galaxy0030')
reg = pf.h.all_data()

key_list = ['dynamical_time','Density','dynamical_time','density',
	'dynamical_time', 'temperature', 'dynamical_time', 'particle_mass',
	'dynamical_time', 'cooling_time', 'dynamical_time', 'cooling_time',
	'dynamical_time', 'cooling_time', 'dynamical_time', 'Density',
	'dynamical_time','density','dynamical_time']

for key in key_list:
    print key, ' ', reg[key].size
```

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/832

**Comment by ngoldbaum** [comment]
I still think this is a good idea. That said, it's probably too disruptive for any 3.x release, so I'm going to add a 4.0 label.

**Comment by chummels** [comment]
This topic was just discussed at a yt-4.0 release meeting.  It was agreed that in yt-4.0, we will accept both string and tuple field names.  If someone specifies a string field name and there is any ambiguity if there are two potential tuple fields that could be accessed, the code will error out with an error message requiring the user to be more explicit. 

The issue was raised that it might be confusing to some users that certain fields differ only by capitalization (e.g., "Density" and "density" for the Enzo frontend: ("Enzo", "Density") and ("gas", "density")), but the consensus was to remain case-sensitive, and just include a note in the Field documentation that this was the expected behavior.

**Comment by chummels** [comment]
This issue is a repeat of Issue #1467 .  Closing this one so we are only tracking it with one issue.
